#lang info
(define collection "calendar")
(define deps '("base" "git://github.com/Antigen-1/hasket.git" "libnotify"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/calendar.scrbl" ())))
(define pkg-desc "My Calendar App")
(define version "0.0")
(define pkg-authors '(zhanghao))
(define license '(Apache-2.0 OR MIT))
(define raco-commands (list (list "calendar" '(submod calendar main) "My calendar app" #f)))
